site_name: Dart Programming
site_url: https://dart.monkypython.com/
docs_dir: 'docs'
nav:
    - Home: index.md
    - About: about.md
theme:
  name: 'material'
  custom_dir: 'theme'
  language: 'en'
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode
    - scheme: slate
      primary: red
      accent: red
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

# Copyright
copyright: 'Copyright &copy; 2021 MonkyPython Labs'

# Customization
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/MonkiyPython
    - icon: fontawesome/brands/gitter
      link: https://gitter.im/MonkyPython_
    - icon: fontawesome/brands/facebook
      link: https://www.facebook.com/monkypython
    - icon: fontawesome/brands/twitter
      link: https://twitter.com/PythonMonky
    - icon: fontawesome/brands/linkedin
      link: https://www.linkedin.com/company/monkypython/
    - icon: fontawesome/brands/instagram
      link: https://instagram.com/monky_python
